
server:
  servlet:
    contextPath: /api
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database: mysql
tenant-id: wbmrp64n
public-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFyWWJ2WG1BbnlIM3FVQlNOWmp3SgpyMlpjN0pKL1BsRU94VzlmTlRiQUI2cWd2azh3dktNemFnclpoMXdFcG54SjAyY3QvdyttUVl5akRKTXJnUHNsCnpyZnNzVnlKTlpENlNlRmo1RWxYVm4yc2ZNaDlKSVY4SURVUUFMcm5RRDloaTEzSUpTVSs4V1ViSUhFRTlDU0MKY3hKVVg3YThOREJOUS9XWGlQN3BXa2NWU040VVBodGdZcDhJNzIwQ3RaYlRMeWU4VmxmUzJBaHNiYUpZVzNqUApzc2tGUyt0R3V2Q0tlUVhJTEdEN3AydEhFWHU1cC9SY3FrMnJlQzQ5TzI4WGQrZ1VDSkc2a0RNODVlV0hXMHlLCktlWFJBR1RqVkNrT2grT00ydHNZbHhyMkdyblVnd20rUklkaTFxWXdUdzZBZjg0Z3hYQTY1NGQ0S1JDVDNta3cKNDJmQzFXVHhFWElWYkprZjZQQll1Q1pxZ1hKTDhqblpjNTBmaVM3a0Vra3pFYXJ4c2xFWnlpU0xTSE1jd3JGcwp4bGgrWFVLUmtURlgyNDd3NkhrTnlEMUhTek5mZFl4MnluTXZ4b205OVUxR2tnUUlQR1NVWXluYW9LRVFTSFNKClZSL0FEc09WRmhDRmV6RVpvYzZ3WlhJS2V2N0VTdGwyb0MwSDU3d3RzdE13c1NnS1RLM1UzcFM2clpwQUJFanMKbkMwTnR6SXQzS3JFS2NUMWw0NllENnhVYWlxZWdNcndtalJrREQxclJERWZyYXdQT2Z1M1UwZk5oUHNmSkR0QwpRYmtPRE5OTWJ4dVphei85Uis5MFpBekl3RDNuSGw5NlordHRNTFZxVFJ3aWJQZzl4QjA1QjhkbEFSYXgxalg0CkVkRThsVWxDb3hKRFNsLzZISEJlUWRVQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
geoapify-key: a9b12a2a2ae0491cb7874bbf0fab7115
otm-key: 5ae2e3f221c38a28845f05b6ce586eafaea5bfb2ddf88b18ba024adf
dev-mode: true
spotify:
  client-id: 1aeeb16afb1944e19a21464aee4e0143
  client-secret: af0dbca1fa53401889a89fe8999b0349
  redirect-uri: http://localhost:8080/spotify/auth-callback
  scope: playlist-read-private,playlist-modify-private,playlist-modify-private,user-read-private,user-read-email
logging:
  level:
    road.trip: INFO
    org.hibernate: WARN